steps:
  - name: gcr.io/cloud-builders/docker
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/elysia/elysia:$COMMIT_SHA'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/elysia/elysia:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'bun-elysia'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/elysia/elysia:$COMMIT_SHA'
      - '--region=us-central1'
      - '--cpu=1'
      - '--memory=1024Mi'
      - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/elysia/elysia:$COMMIT_SHA'
logsBucket: 'gs://sharingsession-bucket/logs'